// <auto-generated />
namespace IDH7A1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addnotnullcontraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addnotnullcontraints));
        
        string IMigrationMetadata.Id
        {
            get { return "201803311150024_Add not null contraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
